name: strive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/homeElem.png
    - assets/images/homeImgTwo.png
    - assets/images/money.png
    - assets/images/cardMoney.png
    - assets/images/ruppes.png
    - assets/images/oon.png
    - assets/images/thee.png
    - assets/images/tte.png
    - assets/images/oosf.png
    - assets/images/rocket.png
